exports.express = {
  logo: '/images/express.jpg',
  name: 'Express',
  men: {
    shirts_and_ties: 'http://www.express.com/shirts-ties-49/control/show/80/index.cat',
    t_shirts: 'http://www.express.com/tees-henleys-844/control/show/80/index.cat',
    polos: 'http://www.express.com/polos-690/control/show/80/index.cat',
    sweatshirts: 'http://www.express.com/hoodies-sweatshirts-836/control/show/80/index.cat',
    blazers: 'http://www.express.com/blazers-vests-1181/control/show/80/index.cat',
    jackets: 'http://www.express.com/jackets-692/control/show/80/index.cat',
    sweaters: 'http://www.express.com/sweaters-60/control/show/80/index.cat',
    coats: 'http://www.express.com/coats-outerwear-97/control/show/80/index.cat',
    shorts: 'http://www.express.com/shorts-swim-612/control/show/80/index.cat',
    jeans: 'http://www.express.com/jeans-62/control/show/80/index.cat',
    underwear: 'http://www.express.com/underwear-79/control/show/80/index.cat',
    swimwear: 'http://www.express.com/shorts-swim-612/control/show/80/index.cat',
    shoes: 'http://www.express.com/shoes-boots-794/control/show/80/index.cat',
    socks: 'http://www.express.com/socks-89/control/show/80/index.cat',
    watches: 'http://www.express.com/watches-845/control/show/80/index.cat',
    belts: 'http://www.express.com/accessories-belts-73/control/show/80/index.cat',
    hats: 'http://www.express.com/hats-scarves-861/control/show/80/index.cat',
    sunglasses: 'http://www.express.com/sunglasses-583/control/show/80/index.cat'
  },
  women: {
    dresses: 'http://www.express.com/dresses-22/control/show/12/index.cat',
    tops: 'http://www.express.com/tops-tees-9/control/show/80/index.cat',
    t_shirts: 'http://www.express.com/shirts-blouses-721/control/show/80/index.cat',
    sweaters: 'http://www.express.com/sweaters-20/control/show/80/index.cat',
    jackets: 'http://www.express.com/jackets-32/control/show/80/index.cat',
    coats: 'http://www.express.com/coats-outerwear-33/control/show/80/index.cat',
    leggings: 'http://www.express.com/leggings-609/control/show/80/index.cat',
    shorts: 'http://www.express.com/shorts-31/control/show/80/index.cat',
    skirts: 'http://www.express.com/skirts-23/control/show/80/index.cat',
    handbags: 'http://www.express.com/handbags-36/control/show/80/index.cat',
    shoes: 'http://www.express.com/shoes-sandals-489/control/show/80/index.cat',
    jeans: 'http://www.express.com/jeans-24/control/show/80/index.cat',
    pants: 'http://www.express.com/pants-28/control/show/80/index.cat',
    lingerie: '',
    socks: '',
    swimwear: '',
    watches: 'http://www.express.com/watches-1087/control/show/80/index.cat',
    belts: 'http://www.express.com/belts-38/control/show/80/index.cat',
    hats: 'http://www.express.com/fashion-scarves-hats-37/control/show/80/index.cat',
    sunglasses: 'http://www.express.com/sunglasses-565/control/show/80/index.cat'
  }
};

exports.handm = {
  logo: '/images/hm.png',
  name: 'H&M',
  men: {
    shirts_and_ties: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294956433',
    t_shirts: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294927206',
    polos: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294927206',
    sweatshirts: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294924882',
    blazers: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294924830',
    jackets: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294924830',
    sweaters: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294927521',
    coats: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294927833',
    shorts: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294952162',
    jeans: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294956231',
    underwear: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294923978',
    swimwear: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294952307',
    shoes: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294957721',
    socks: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294958404',
    watches: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294926526',
    belts: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294927569',
    hats: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294923718',
    sunglasses: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294919597'
  },
  women: {
    dresses: 'http://www.hm.com/us/subdepartment/LADIES?Nr=4294960648',
    tops: 'http://www.hm.com/us/subdepartment/LADIES?Nr=4294956943',
    t_shirts: 'http://www.hm.com/us/subdepartment/LADIES?Nr=4294956943',
    sweaters: 'http://www.hm.com/us/subdepartment/LADIES?Nr=429495694',
    jackets: 'http://www.hm.com/us/subdepartment/LADIES?Nr=4294963529',
    coats: 'http://www.hm.com/us/subdepartment/LADIES?Nr=4294963529',
    leggings: 'http://www.hm.com/us/subdepartment/LADIES?Nr=4294960522',
    shorts: 'http://www.hm.com/us/subdepartment/LADIES?Nr=4294960292',
    skirts: 'http://www.hm.com/us/subdepartment/LADIES?Nr=4294962650',
    handbags: 'http://www.hm.com/us/subdepartment/LADIES?Nr=4294926110',
    shoes: 'http://www.hm.com/us/subdepartment/LADIES?Nr=4294959277',
    jeans: 'http://www.hm.com/us/subdepartment/LADIES?Nr=4294962118',
    pants: 'http://www.hm.com/us/subdepartment/LADIES?Nr=4294961894',
    lingerie: 'http://www.hm.com/us/subdepartment/LADIES?Nr=4294929212',
    socks: 'http://www.hm.com/us/subdepartment/LADIES?Nr=4294963208',
    swimwear: 'http://www.hm.com/us/subdepartment/LADIES?Nr=4294956943',
    watches: 'http://www.hm.com/us/subdepartment/LADIES?Nr=4294928276',
    belts: 'http://www.hm.com/us/subdepartment/LADIES?Nr=4294934301',
    hats: 'http://www.hm.com/us/subdepartment/LADIES?Nr=4294928700',
    sunglasses: 'http://www.hm.com/us/subdepartment/LADIES?Nr=4294919701'
  }
};

exports.handm = {
  logo: '/images/hm.png',
  name: 'Macys',
  men: {
    shirts_and_ties: 'http://www1.macys.com/shop/mens-clothing/mens-shirts?id=20626',
    t_shirts: 'http://www1.macys.com/shop/mens-clothing/mens-t-shirts?id=30423',
    polos: 'http://www1.macys.com/shop/mens-clothing/mens-polos?id=20640',
    sweatshirts: 'http://www1.macys.com/shop/mens-clothing/hoodies-for-men?id=25995',
    blazers: 'http://www1.macys.com/shop/mens-clothing/mens-blazers?id=16499',
    jackets: 'http://www1.macys.com/shop/mens-clothing/mens-coats?id=3763',
    sweaters: 'http://www1.macys.com/shop/mens-clothing/mens-sweaters?id=4286',
    coats: 'http://www1.macys.com/shop/mens-clothing/mens-coats?id=3763',
    shorts: 'http://www1.macys.com/shop/mens-clothing/mens-shorts?id=3310',
    jeans: 'http://www1.macys.com/shop/mens-clothing/mens-jeans?id=11221',
    underwear: 'http://www1.macys.com/shop/mens-clothing/mens-underwear?id=57',
    swimwear: 'http://www1.macys.com/shop/mens-clothing/mens-swimwear?id=3291',
    shoes: 'http://www1.macys.com/shop/mens-clothing/mens-shoes?id=65',
    socks: 'http://www1.macys.com/shop/mens-clothing/mens-socks?id=18245',
    watches: 'http://www1.macys.com/shop/jewelry-watches/mens-watches?id=57386',
    belts: 'http://www1.macys.com/shop/mens-clothing/mens-belts?id=47665',
    hats: 'http://www1.macys.com/shop/mens-clothing/hats-gloves-scarves?id=47657',
    sunglasses: 'http://www1.macys.com/shop/mens-clothing/mens-sunglasses?id=58170'
  },
  women: {
    dresses: '',
    tops: '',
    t_shirts: '',
    sweaters: '',
    jackets: '',
    coats: '',
    leggings: '',
    shorts: '',
    skirts: '',
    handbags: '',
    shoes: '',
    jeans: '',
    pants: '',
    lingerie: '',
    socks: '',
    swimwear: '',
    watches: '',
    belts: '',
    hats: '',
    sunglasses: ''
  }
};

exports.gap = {
  logo: '',
  name: 'GAP',
  men: {
    shirts_and_ties: 'http://www.gap.com/browse/category.do?cid=15043',
    t_shirts: 'http://www.gap.com/browse/category.do?cid=5225',
    polos: '',
    sweatshirts: '',
    blazers: '',
    jackets: '',
    sweaters: '',
    coats: '',
    shorts: '',
    jeans: '',
    underwear: '',
    swimwear: '',
    shoes: '',
    socks: '',
    watches: '',
    belts: '',
    hats: '',
    sunglasses: ''
  },
  women: {
    dresses: '',
    tops: '',
    t_shirts: '',
    sweaters: '',
    jackets: '',
    coats: '',
    leggings: '',
    shorts: '',
    skirts: '',
    handbags: '',
    shoes: '',
    jeans: '',
    pants: '',
    lingerie: '',
    socks: '',
    swimwear: '',
    watches: '',
    belts: '',
    hats: '',
    sunglasses: ''
  }
};

exports.armani_exchange = {
  logo: '',
  name: 'Armani Exchange',
  men: {
    shirts_and_ties: '',
    t_shirts: '',
    polos: '',
    sweatshirts: '',
    blazers: '',
    jackets: '',
    sweaters: '',
    coats: '',
    shorts: '',
    jeans: '',
    underwear: '',
    swimwear: '',
    shoes: '',
    socks: '',
    watches: '',
    belts: '',
    hats: '',
    sunglasses: ''
  },
  women: {
    dresses: '',
    tops: '',
    t_shirts: '',
    sweaters: '',
    jackets: '',
    coats: '',
    leggings: '',
    shorts: '',
    skirts: '',
    handbags: '',
    shoes: '',
    jeans: '',
    pants: '',
    lingerie: '',
    socks: '',
    swimwear: '',
    watches: '',
    belts: '',
    hats: '',
    sunglasses: ''
  }
};
