exports.express = {
  logo: '/images/express.jpg',
  name: 'Express',
  men: {
    shirts_and_ties: 'http://www.express.com/shirts-ties-49/control/show/80/index.cat',
    t_shirts: 'http://www.express.com/tees-henleys-844/control/show/80/index.cat',
    polos: 'http://www.express.com/polos-690/control/show/80/index.cat',
    sweatshirts: 'http://www.express.com/hoodies-sweatshirts-836/control/show/80/index.cat',
    blazers: 'http://www.express.com/blazers-vests-1181/control/show/80/index.cat',
    jackets: 'http://www.express.com/jackets-692/control/show/80/index.cat',
    sweaters: 'http://www.express.com/sweaters-60/control/show/80/index.cat',
    coats: 'http://www.express.com/coats-outerwear-97/control/show/80/index.cat',
    shorts: 'http://www.express.com/shorts-swim-612/control/show/80/index.cat',
    jeans: 'http://www.express.com/jeans-62/control/show/80/index.cat',
    underwear: 'http://www.express.com/underwear-79/control/show/80/index.cat',
    swimwear: 'http://www.express.com/shorts-swim-612/control/show/80/index.cat',
    shoes: 'http://www.express.com/shoes-boots-794/control/show/80/index.cat',
    socks: 'http://www.express.com/socks-89/control/show/80/index.cat',
    watches: 'http://www.express.com/watches-845/control/show/80/index.cat',
    belts: 'http://www.express.com/accessories-belts-73/control/show/80/index.cat',
    hats: 'http://www.express.com/hats-scarves-861/control/show/80/index.cat',
    sunglasses: 'http://www.express.com/sunglasses-583/control/show/80/index.cat'
  },
  women: {
    dresses: 'http://www.express.com/dresses-22/control/show/12/index.cat',
    tops: 'http://www.express.com/tops-tees-9/control/show/80/index.cat',
    t_shirts: 'http://www.express.com/shirts-blouses-721/control/show/80/index.cat',
    sweaters: 'http://www.express.com/sweaters-20/control/show/80/index.cat',
    jackets: 'http://www.express.com/jackets-32/control/show/80/index.cat',
    coats: 'http://www.express.com/coats-outerwear-33/control/show/80/index.cat',
    leggings: 'http://www.express.com/leggings-609/control/show/80/index.cat',
    shorts: 'http://www.express.com/shorts-31/control/show/80/index.cat',
    skirts: 'http://www.express.com/skirts-23/control/show/80/index.cat',
    handbags: 'http://www.express.com/handbags-36/control/show/80/index.cat',
    shoes: 'http://www.express.com/shoes-sandals-489/control/show/80/index.cat',
    jeans: 'http://www.express.com/jeans-24/control/show/80/index.cat',
    pants: 'http://www.express.com/pants-28/control/show/80/index.cat',
    lingerie: '',
    socks: '',
    swimwear: '',
    watches: 'http://www.express.com/watches-1087/control/show/80/index.cat',
    belts: 'http://www.express.com/belts-38/control/show/80/index.cat',
    hats: '',
    sunglasses: 'http://www.express.com/sunglasses-565/control/show/80/index.cat'
  }
};

exports.handm = {
  logo: '/images/hm.png',
  name: 'H&M',
  men: {
    shirts_and_ties: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294956433',
    t_shirts: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294927206',
    polos: '',
    sweatshirts: '',
    blazers: '',
    jackets: '',
    sweaters: '',
    coats: '',
    shorts: '',
    jeans: '',
    underwear: '',
    swimwear: '',
    shoes: '',
    socks: '',
    watches: '',
    belts: '',
    hats: '',
    sunglasses: ''
  },
  women: {
    dresses: '',
    tops: '',
    t_shirts: '',
    sweaters: '',
    jackets: '',
    coats: '',
    leggings: '',
    shorts: '',
    skirts: '',
    handbags: '',
    shoes: '',
    jeans: '',
    pants: '',
    lingerie: '',
    socks: '',
    swimwear: '',
    watches: '',
    belts: '',
    hats: '',
    sunglasses: ''
  }
};

exports.gap = {
  logo: '',
  name: 'GAP',
  men: {
    shirts_and_ties: 'http://www.gap.com/browse/category.do?cid=15043',
    t_shirts: 'http://www.gap.com/browse/category.do?cid=5225',
    polos: '',
    sweatshirts: '',
    blazers: '',
    jackets: '',
    sweaters: '',
    coats: '',
    shorts: '',
    jeans: '',
    underwear: '',
    swimwear: '',
    shoes: '',
    socks: '',
    watches: '',
    belts: '',
    hats: '',
    sunglasses: ''
  },
  women: {
    dresses: '',
    tops: '',
    t_shirts: '',
    sweaters: '',
    jackets: '',
    coats: '',
    leggings: '',
    shorts: '',
    skirts: '',
    handbags: '',
    shoes: '',
    jeans: '',
    pants: '',
    lingerie: '',
    socks: '',
    swimwear: '',
    watches: '',
    belts: '',
    hats: '',
    sunglasses: ''
  }
};

exports.armani_exchange = {
  logo: '',
  name: 'Armani Exchange',
  men: {
    shirts_and_ties: '',
    t_shirts: '',
    polos: '',
    sweatshirts: '',
    blazers: '',
    jackets: '',
    sweaters: '',
    coats: '',
    shorts: '',
    jeans: '',
    underwear: '',
    swimwear: '',
    shoes: '',
    socks: '',
    watches: '',
    belts: '',
    hats: '',
    sunglasses: ''
  },
  women: {
    dresses: '',
    tops: '',
    t_shirts: '',
    sweaters: '',
    jackets: '',
    coats: '',
    leggings: '',
    shorts: '',
    skirts: '',
    handbags: '',
    shoes: '',
    jeans: '',
    pants: '',
    lingerie: '',
    socks: '',
    swimwear: '',
    watches: '',
    belts: '',
    hats: '',
    sunglasses: ''
  }
};
