exports.express = {
  logo: '/images/express.jpg',
  name: 'Express',
  men: {
    shirts_and_ties: 'http://www.express.com/shirts-ties-49/control/show/80/index.cat',
    t_shirts: 'http://www.express.com/tees-henleys-844/control/show/80/index.cat',
    polos: 'http://www.express.com/polos-690/control/show/80/index.cat',
    sweatshirts: 'http://www.express.com/hoodies-sweatshirts-836/control/show/80/index.cat',
    blazers: 'http://www.express.com/blazers-vests-1181/control/show/80/index.cat',
    jackets: 'http://www.express.com/jackets-692/control/show/80/index.cat',
    sweaters: 'http://www.express.com/sweaters-60/control/show/80/index.cat',
    coats: 'http://www.express.com/coats-outerwear-97/control/show/80/index.cat',
    shorts: 'http://www.express.com/shorts-swim-612/control/show/80/index.cat',
    jeans: '',
    underwear: '',
    swimwear: '',
    shoes: '',
    socks: '',
    watches: '',
    belts: '',
    hats: '',
    sunglasses: ''
  },
  women: {
    dresses: '',
    tops: '',
    t_shirts: '',
    sweaters: '',
    jackets: '',
    coats: '',
    leggings: '',
    shorts: '',
    skirts: '',
    handbags: '',
    shoes: '',
    jeans: '',
    pants: '',
    lingerie: '',
    socks: '',
    swimwear: '',
    watches: '',
    belts: '',
    hats: '',
    sunglasses: ''
  }
};

exports.handm = {
  logo: '/images/hm.png',
  name: 'H&M',
  men: {
    shirts_and_ties: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294956433',
    t_shirts: 'http://www.hm.com/us/subdepartment/MEN?Nr=4294927206',
    polos: '',
    sweatshirts: '',
    blazers: '',
    jackets: '',
    sweaters: '',
    coats: '',
    shorts: '',
    jeans: '',
    underwear: '',
    swimwear: '',
    shoes: '',
    socks: '',
    watches: '',
    belts: '',
    hats: '',
    sunglasses: ''
  },
  women: {
    dresses: '',
    tops: '',
    t_shirts: '',
    sweaters: '',
    jackets: '',
    coats: '',
    leggings: '',
    shorts: '',
    skirts: '',
    handbags: '',
    shoes: '',
    jeans: '',
    pants: '',
    lingerie: '',
    socks: '',
    swimwear: '',
    watches: '',
    belts: '',
    hats: '',
    sunglasses: ''
  }
};

exports.gap = {
  logo: '',
  name: 'GAP',
  men: {
    shirts_and_ties: 'http://www.gap.com/browse/category.do?cid=15043',
    t_shirts: 'http://www.gap.com/browse/category.do?cid=5225',
    polos: '',
    sweatshirts: '',
    blazers: '',
    jackets: '',
    sweaters: '',
    coats: '',
    shorts: '',
    jeans: '',
    underwear: '',
    swimwear: '',
    shoes: '',
    socks: '',
    watches: '',
    belts: '',
    hats: '',
    sunglasses: ''
  },
  women: {
    dresses: '',
    tops: '',
    t_shirts: '',
    sweaters: '',
    jackets: '',
    coats: '',
    leggings: '',
    shorts: '',
    skirts: '',
    handbags: '',
    shoes: '',
    jeans: '',
    pants: '',
    lingerie: '',
    socks: '',
    swimwear: '',
    watches: '',
    belts: '',
    hats: '',
    sunglasses: ''
  }
};

exports.armani_exchange = {
  logo: '',
  name: 'Armani Exchange',
  men: {
    shirts_and_ties: '',
    t_shirts: '',
    polos: '',
    sweatshirts: '',
    blazers: '',
    jackets: '',
    sweaters: '',
    coats: '',
    shorts: '',
    jeans: '',
    underwear: '',
    swimwear: '',
    shoes: '',
    socks: '',
    watches: '',
    belts: '',
    hats: '',
    sunglasses: ''
  },
  women: {
    dresses: '',
    tops: '',
    t_shirts: '',
    sweaters: '',
    jackets: '',
    coats: '',
    leggings: '',
    shorts: '',
    skirts: '',
    handbags: '',
    shoes: '',
    jeans: '',
    pants: '',
    lingerie: '',
    socks: '',
    swimwear: '',
    watches: '',
    belts: '',
    hats: '',
    sunglasses: ''
  }
};
